# Generated by Django 4.2.8 on 2023-12-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_de', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_uk', models.CharField(max_length=255, null=True)),
                ('name_ar', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('organizer', models.CharField(max_length=255)),
                ('organizer_en', models.CharField(max_length=255, null=True)),
                ('organizer_de', models.CharField(max_length=255, null=True)),
                ('organizer_ru', models.CharField(max_length=255, null=True)),
                ('organizer_uk', models.CharField(max_length=255, null=True)),
                ('organizer_ar', models.CharField(max_length=255, null=True)),
                ('organizer_fr', models.CharField(max_length=255, null=True)),
                ('responsible_person', models.CharField(max_length=255)),
                ('responsible_person_en', models.CharField(max_length=255, null=True)),
                ('responsible_person_de', models.CharField(max_length=255, null=True)),
                ('responsible_person_ru', models.CharField(max_length=255, null=True)),
                ('responsible_person_uk', models.CharField(max_length=255, null=True)),
                ('responsible_person_ar', models.CharField(max_length=255, null=True)),
                ('responsible_person_fr', models.CharField(max_length=255, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('location_en', models.CharField(max_length=255, null=True)),
                ('location_de', models.CharField(max_length=255, null=True)),
                ('location_ru', models.CharField(max_length=255, null=True)),
                ('location_uk', models.CharField(max_length=255, null=True)),
                ('location_ar', models.CharField(max_length=255, null=True)),
                ('location_fr', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255)),
                ('category_en', models.CharField(max_length=255, null=True)),
                ('category_de', models.CharField(max_length=255, null=True)),
                ('category_ru', models.CharField(max_length=255, null=True)),
                ('category_uk', models.CharField(max_length=255, null=True)),
                ('category_ar', models.CharField(max_length=255, null=True)),
                ('category_fr', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='event_photos/')),
                ('items_to_bring', models.TextField(blank=True, null=True)),
                ('items_to_bring_en', models.TextField(blank=True, null=True)),
                ('items_to_bring_de', models.TextField(blank=True, null=True)),
                ('items_to_bring_ru', models.TextField(blank=True, null=True)),
                ('items_to_bring_uk', models.TextField(blank=True, null=True)),
                ('items_to_bring_ar', models.TextField(blank=True, null=True)),
                ('items_to_bring_fr', models.TextField(blank=True, null=True)),
                ('participation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name.', max_length=255)),
                ('last_name', models.CharField(help_text='Enter your last name.', max_length=255)),
                ('email', models.EmailField(help_text='Enter a valid email address.', max_length=254)),
                ('phone_number', models.CharField(help_text='Enter a valid phone number containing only digits.', max_length=20)),
                ('date_of_birth', models.DateField(help_text='Enter your date of birth.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsApp.event')),
            ],
        ),
    ]
