# Generated by Django 4.2.8 on 2023-12-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersApp', '0001_initial'),  # Зависимость от начальной миграции вашего приложения
    ]

    operations = [
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='swiper_image/')),
            ],
        ),
    ]
